# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: federated_comm.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'federated_comm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x66\x65\x64\x65rated_comm.proto\x12\tfederated\"\x1f\n\nClientInfo\x12\x11\n\tclient_id\x18\x01 \x01(\x05\"8\n\x14RegistrationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x9b\x01\n\x0bTaskRequest\x12\x11\n\tround_num\x18\x01 \x01(\x05\x12\x11\n\ttask_type\x18\x02 \x01(\t\x12\x14\n\x0cmodel_params\x18\x03 \x01(\x0c\x12\x15\n\rlearning_rate\x18\x04 \x01(\x02\x12\x0e\n\x06\x65pochs\x18\x05 \x01(\x05\x12\x12\n\nbatch_size\x18\x06 \x01(\x05\x12\x15\n\ruse_test_data\x18\x07 \x01(\x08\"y\n\x0cTaskResponse\x12\x11\n\tclient_id\x18\x01 \x01(\x05\x12\x16\n\x0eupdated_params\x18\x02 \x01(\x0c\x12\x0c\n\x04loss\x18\x03 \x01(\x02\x12\x10\n\x08\x61\x63\x63uracy\x18\x04 \x01(\x02\x12\x0f\n\x07samples\x18\x05 \x01(\x05\x12\r\n\x05\x65rror\x18\x06 \x01(\t2\x99\x01\n\x10\x46\x65\x64\x65ratedService\x12\x42\n\x08Register\x12\x15.federated.ClientInfo\x1a\x1f.federated.RegistrationResponse\x12\x41\n\nTaskStream\x12\x17.federated.TaskResponse\x1a\x16.federated.TaskRequest(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'federated_comm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTINFO']._serialized_start=35
  _globals['_CLIENTINFO']._serialized_end=66
  _globals['_REGISTRATIONRESPONSE']._serialized_start=68
  _globals['_REGISTRATIONRESPONSE']._serialized_end=124
  _globals['_TASKREQUEST']._serialized_start=127
  _globals['_TASKREQUEST']._serialized_end=282
  _globals['_TASKRESPONSE']._serialized_start=284
  _globals['_TASKRESPONSE']._serialized_end=405
  _globals['_FEDERATEDSERVICE']._serialized_start=408
  _globals['_FEDERATEDSERVICE']._serialized_end=561
# @@protoc_insertion_point(module_scope)
